// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxpwlimdbkmwvtnpmmmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cHdsaW1kYmttd3Z0bnBtbW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzA2MTAsImV4cCI6MjA2ODI0NjYxMH0.rbghPjG-FeR4R8sGc0Mw4RE4rOlSyuhEU8pD_TQtGUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});