// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkwhkyhmyskirkplhcmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrd2hreWhteXNraXJrcGxoY210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzkxMjAsImV4cCI6MjA3MDkxNTEyMH0.noWkjgKkYinzuyvDh9i3GBSZ_w6dP4IzX0WqfN4pDIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});